# Generated by Django 4.2.1 on 2024-06-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture', 'date')},
        ),
    ]
