# Generated by Django 4.2.1 on 2024-06-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_email_alter_student_enroll_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('teacher', 'start_time')},
        ),
    ]
